### PR TITLE
add `--renderer` arg which takes `textual`/`graphical`

### PR DESCRIPTION
**Pull request by mikemoraned**
- note that needed to use pinned version of turtle to work around a build issue with `cocoa` library

### CODE REVIEW

**Comment by dvberkel** [comment]
Sweet. This is very cool. Thanks for your contribution

I will be merging this soon, but I need to find some time to change the description of the workbook.

**Comment by mikemoraned** [comment]
👋 just checking back to see if you'd like any help from me on this

**Comment by dvberkel** [comment]
Hi @mikemoraned 
I totally forgot about this pull request. Sorry about that. 

I will look at it tomorrow

**Comment by dvberkel** [comment]
@mikemoraned Thanks for your contribution! I will start a contributors list and mention you there

**Pull request merged**
